DELETE FROM CURRENCY;
INSERT INTO CURRENCY(ID,NAME,ISO3) VALUES (1, 'Dollar', 'USD');
INSERT INTO CURRENCY(ID,NAME,ISO3) VALUES (2, 'British Pound', 'GBP');
INSERT INTO CURRENCY(ID,NAME,ISO3) VALUES (3, 'Euro', 'EUR');