DELETE FROM PRICE_POINT;
DELETE FROM CURRENCY;
DELETE FROM PRODUCT;
INSERT INTO PRODUCT(ID,NAME,DESCRIPTION) VALUES (1, 'dummy product', 'A dummy product for testing purposes.');
INSERT INTO CURRENCY(ID,NAME,ISO3) VALUES (1, 'Dollar', 'USD');
INSERT INTO PRICE_POINT(ID,PRICE,CURRENCY_ID,PRODUCT_ID) VALUES (1, 4.56, 1,1);